"""Tests for compute_metrics u_for_dynamics override.

Verifies that:
- passing u_for_dynamics changes dynamics_violation_known and dynamics_violation_true
- dynamics_violation_learned is NOT affected by u_for_dynamics (it always uses u_corrected)
- default (u_for_dynamics=None) behaviour is backward-compatible
"""

from __future__ import annotations

import diffrax
import jax
import jax.numpy as jnp

from made.evaluation.metrics import compute_metrics
from made.models import AugmentedDynamics, ZeroResidual
from made.physics import KinematicBicycle, build_system_for_model


def _make_kinbicycle_trajectory(n_steps: int = 4, dt: float = 0.1):
    """Build a short kinematic-bicycle trajectory via Heun integration."""
    physics = KinematicBicycle()
    params = jnp.array([2.7])
    x0 = jnp.array([0.0, 0.0, 0.0, 8.0])
    u_step = jnp.array([0.1, 0.5])

    states = [x0]
    x = x0
    for _ in range(n_steps):
        sol = diffrax.diffeqsolve(
            diffrax.ODETerm(
                lambda t, y, args: physics.vector_field(y, args["control"], params, t)
            ),
            diffrax.Heun(),
            t0=0.0,
            t1=dt,
            dt0=dt,
            y0=x,
            args={"control": u_step},
            stepsize_controller=diffrax.ConstantStepSize(),
            saveat=diffrax.SaveAt(t1=True),
            max_steps=16,
        )
        x = sol.ys[0]
        states.append(x)

    x_traj = jnp.stack(states)          # (n_steps+1, 4)
    u_traj = jnp.tile(u_step, (n_steps, 1))  # (n_steps, 2)
    return x_traj, u_traj, params, physics


def test_u_for_dynamics_changes_dyn_k_and_dyn_t():
    """Passing a different u_for_dynamics must change Dyn.-K and Dyn.-T."""
    x_traj, u_gt, params, physics = _make_kinbicycle_trajectory()
    _, constraints = build_system_for_model("kinematic_bicycle", "kinematic_bicycle")
    stub_dynamics = AugmentedDynamics(physics, ZeroResidual(physics.state_dim))
    dt = 0.1

    # u_corrected is all zeros (baseline placeholder)
    u_zero = jnp.zeros_like(u_gt)

    metrics_default = compute_metrics(
        x_traj,
        u_zero,
        x_traj,
        u_gt,
        constraints,
        physics,
        stub_dynamics,
        params,
        dt,
        dynamics_true=physics,
        true_params=params,
        u_for_dynamics=None,  # default: uses u_zero for dynamics metrics
    )

    metrics_gt = compute_metrics(
        x_traj,
        u_zero,
        x_traj,
        u_gt,
        constraints,
        physics,
        stub_dynamics,
        params,
        dt,
        dynamics_true=physics,
        true_params=params,
        u_for_dynamics=u_gt,  # override: uses ground-truth controls
    )

    # Dyn.-K and Dyn.-T must differ between the two calls
    assert metrics_default["dynamics_violation_known"] != metrics_gt["dynamics_violation_known"], (
        "u_for_dynamics override had no effect on dynamics_violation_known"
    )
    assert metrics_default["dynamics_violation_true"] != metrics_gt["dynamics_violation_true"], (
        "u_for_dynamics override had no effect on dynamics_violation_true"
    )

    # With ground-truth controls, Dyn.-K should be near zero (trajectory was
    # generated by those exact controls with the same Heun stencil)
    assert metrics_gt["dynamics_violation_known"] < 1e-9, (
        f"Expected near-zero Dyn.-K with ground-truth controls, got "
        f"{metrics_gt['dynamics_violation_known']}"
    )

    # With zero controls, Dyn.-K should be substantially larger
    assert metrics_default["dynamics_violation_known"] > 0.01, (
        f"Expected nonzero Dyn.-K with zero controls, got "
        f"{metrics_default['dynamics_violation_known']}"
    )


def test_dynamics_violation_learned_unaffected_by_u_for_dynamics():
    """dynamics_violation_learned must use u_corrected regardless of u_for_dynamics."""
    x_traj, u_gt, params, physics = _make_kinbicycle_trajectory()
    _, constraints = build_system_for_model("kinematic_bicycle", "kinematic_bicycle")
    stub_dynamics = AugmentedDynamics(physics, ZeroResidual(physics.state_dim))
    dt = 0.1

    u_zero = jnp.zeros_like(u_gt)

    metrics_no_override = compute_metrics(
        x_traj,
        u_zero,
        x_traj,
        u_gt,
        constraints,
        physics,
        stub_dynamics,
        params,
        dt,
        u_for_dynamics=None,
    )

    metrics_with_override = compute_metrics(
        x_traj,
        u_zero,
        x_traj,
        u_gt,
        constraints,
        physics,
        stub_dynamics,
        params,
        dt,
        u_for_dynamics=u_gt,
    )

    assert (
        metrics_no_override["dynamics_violation_learned"]
        == metrics_with_override["dynamics_violation_learned"]
    ), (
        "u_for_dynamics incorrectly affected dynamics_violation_learned: "
        f"{metrics_no_override['dynamics_violation_learned']} vs "
        f"{metrics_with_override['dynamics_violation_learned']}"
    )


def test_default_none_is_backward_compatible():
    """u_for_dynamics=None must produce the same result as omitting the argument."""
    x_traj, u_gt, params, physics = _make_kinbicycle_trajectory()
    _, constraints = build_system_for_model("kinematic_bicycle", "kinematic_bicycle")
    stub_dynamics = AugmentedDynamics(physics, ZeroResidual(physics.state_dim))
    dt = 0.1
    u_zero = jnp.zeros_like(u_gt)

    # Call without the new argument (omitted = default None)
    m_omitted = compute_metrics(
        x_traj, u_zero, x_traj, u_gt, constraints, physics, stub_dynamics, params, dt
    )
    # Call with explicit None
    m_explicit_none = compute_metrics(
        x_traj, u_zero, x_traj, u_gt, constraints, physics, stub_dynamics, params, dt,
        u_for_dynamics=None,
    )

    for key in m_omitted:
        assert m_omitted[key] == m_explicit_none[key], (
            f"Metric '{key}' differs: omitted={m_omitted[key]}, "
            f"explicit_none={m_explicit_none[key]}"
        )
